spring.data.mongodb.uri=mongodb://localhost:27888
spring.data.mongodb.database=VOYAGE
firebase.service-account.path=/Users/vincenzoingenito/eclipse-workspace-2025/voyage-be/src/main/resources/voyage-ed2d0-firebase-adminsdk-fbsvc-7d741f97ec.json
google.places.api.key=AIzaSyBIfPNXvLP64RPgLHjRroVy8ElA3o_uE9I
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true