server.port=9080
spring.application.name=voyage
server.servlet.context-path=/

####### APPLICATION MONITORING ################
info.app.name=Voyage
info.app.description=Voyage
info.app.version=1.0.0

management.server.port=9080
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.live=status
management.endpoints.web.path-mapping.health=health/ready
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoints.web.path-mapping.prometheus=metrics
management.endpoints.web.path-mapping.metrics=actuator
management.endpoints.web.exposure.include=health,metrics,prometheus,live,ready,env,info
management.health.db.enabled=true
management.endpoint.health.show-details=always
####### APPLICATION MONITORING ################
 
######OPENAPI#####################################
springdoc.swagger-ui.path=/openapi/ui
spring.jackson.default-property-inclusion=NON_NULL 

####### LOGGING OUTPUT FORMAT ############
# Must be one of console, json
#######################################
log.output.format=CONSOLE

#######################################
#	PostgreSQL Database Configuration
#######################################
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false

#######################################
#			OPENAPI CONFIGURATION
#######################################
docs.info.contact.name=Vincenzo Ingenito
docs.info.contact.mail=vincenzo.ingenit@hotmail.it
docs.info.contact.url=https://github.com/vincenzo-ingenito
docs.info.termsOfService=www.terms.com
docs.info.summary=Handles configuration items for all other microservices
docs.info.description=Handles configuration items for all other microservices
docs.info.api-id=1
docs.info.title=Voyage

########OPENTELEMETRY################################
otel.propagators=tracecontext,baggage

########CORS################################
cors.allowed-origins=https://voyage-react.onrender.com
########FIREBASE################################
firebase.service-account.path=${FIREBASE_ADMIN_PATH}
firebase.storage.bucket-name=voyage-ed2d0.appspot.com
google.places.api.key=${GOOGLE_PLACE_API_KEY}
# application.properties
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-http-form-post-size=100MB
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false