server.port=9080
spring.application.name=gtw-config
server.servlet.context-path=/

####### APPLICATION MONITORING ################
info.app.name=Gateway Config
info.app.description=Gateway Config for FSE.
info.app.version=1.0.0

management.server.port=9080
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.live=status
management.endpoints.web.path-mapping.health=health-ready
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.endpoints.web.path-mapping.prometheus=metrics
management.endpoints.web.path-mapping.metrics=actuator
management.endpoints.web.exposure.include=health,metrics,prometheus,live,ready,env,info
management.health.db.enabled=true
management.endpoint.health.show-details=always
####### APPLICATION MONITORING ################
 
######OPENAPI#####################################
springdoc.swagger-ui.path=/openapi/ui

spring.jackson.default-property-inclusion = NON_NULL 

####### LOGGING OUTPUT FORMAT ############
# Must be one of console, json
#######################################
log.output.format=console

#######################################
#	Database
#######################################
data.mongodb.uri=mongodb://localhost:27888
data.mongodb.schema-name=FSE_GTW

#######################################
#			OPENAPI CONFIGURATION
#######################################
docs.info.contact.name=Mario Rossi
docs.info.contact.mail=example@mail.com
docs.info.contact.url=www.example.com
docs.info.termsOfService=www.terms.com
docs.info.summary=Handles configuration items for all other microservices
docs.info.description=Handles configuration items for all other microservices
docs.info.api-id=1
docs.info.title=Gateway Config

###################
#	GATEWAY NAME  #
###################
gateway.full-qualified-name=FSE2-GTW-00